### ISSUE TITLE
lone question mark scalar should be quoted, not encoded in Plain Style

### ISSUE THREAD

**Issue by mlwilkerson** [ufirstgroup/ymlr#177]
#### Issue description
The encoding of a single `?` character as a value should be quoted, so as not to be confused with the "?" taken as a _mapping key indicator_.

## Example

Given this Elixir map:

```elixir
%{
  "foo" => [
    42,
    "?",
    "bar"
  ]
}
```

Ymlr 5.0 produces this YML:

```yml
---
foo:
  - 42
  - ?
  - bar
```

The original string "?" is being emitted as a plain `?` without quotation. This seems to result in ambiguity, since the "?" character, in some contexts, is also used to indicate a key in a map.

I first discovered this when I found that [`yaml_elixir`](https://hexdocs.pm/yaml_elixir/readme.html), which is a wrapper around `yamerl`, failed to parse the above Ymlr-produced document, saying that it is malformed YML.

Consider the output of running that YML through the parser tests in [libyaml](https://github.com/yaml/libyaml/blob/master/tests/ReadMe.md).

Write the above YML document to `question.yml` and then:

`cat question.yml | ./tests/run-parser-test-suite`

This shows the various parser events, according to libyaml, as it makes its way through the document:

```
+STR
+DOC
+MAP
=VAL :foo
+SEQ
=VAL :42
+MAP
=VAL :
=VAL :
-MAP
=VAL :bar
-SEQ
-MAP
-DOC
-STR
```

In particular, notice what happens after it recognizes `42` as a value in the sequence (`=VAL :42`). The next event is `+MAP`. It starts a new map. And then it emits two events of `=VAL :`, and then it closes that map with `-MAP`.

I take the two `=VAL :` events as an empty key followed by an empty value. This one key/value pair is the only one in that map.

Why would it do that? I think it would do that if it was interpreting that plain `?` question as a mapping key _indicator_. That puts it in "map mode", scanning for a key, after which it will scan for a value, and so on, until there's an event that would close that map: namely, the `- bar`, which is the next item in the outer sequence.

#### Link to documentation

The spec's [Section 5.3 on Indicators](https://yaml.org/spec/1.2.2/#53-indicator-characters) says:

> "?" (`x3F`, question mark) denotes a [mapping key](https://yaml.org/spec/1.2.2/#nodes).

What does this mapping key do? Example 5.3 in the docs illustrates.

<img width="1127" alt="CleanShot 2023-12-26 at 13 07 14@2x" src="https://github.com/ufirstgroup/ymlr/assets/11575183/58dea409-6e92-46cd-9fa4-5b12c7d8fc66">

In that example, the `?` followed by `space` and then `sky` indicates that `sky` should be treated as a key in a map. The following term `: blue` is taken as the value that goes with the key `sky`.

[Section 7.3.3 on Plain Style](https://yaml.org/spec/1.2.2/#733-plain-style) says:

> Plain scalars must not begin with most [indicators](https://yaml.org/spec/1.2.2/#indicator-characters), as this would cause ambiguity with other YAML constructs. However, the “:”, “?” and “-” [indicators](https://yaml.org/spec/1.2.2/#indicator-characters) may be used as the first character if followed by a non-[space](https://yaml.org/spec/1.2.2/#white-space-characters) “safe” character, as this causes no ambiguity.

Here's how I reason through the implications of that for our case:

Since `?` is an indicator, the only way the line `- ?` could be taken as Plain Style, is if the `?` were _followed by_ a "safe" character.

But since `?` is the entire value, it's not followed by _any_ character, and therefore it's not followed by a _safe_ character. Therefore, the value `?` cannot be encoded in Plain Style; it must be escaped or quoted.

**Comment by mruoss** [comment]
Thanks @mlwilkerson for the extensive description of the issue. Indeed, it seems like we're missing something here. But let me have a look at your PR.
