### ISSUE TITLE
Missing escaping for uppercase "No"

### ISSUE THREAD

**Issue by Zinggi** [ufirstgroup/ymlr#188]
#### Issue description

Similar to https://github.com/ufirstgroup/ymlr/pull/184, I've found another issue with escaping:

```elixir
iex> Ymlr.document!(%{foo: "No"})
"---\nfoo: No\n"
```

correct would be:
```ruby
irb> YAML.dump({"foo"=> "No"})
=> "---\nfoo: 'No'\n"
```

It's already correct for lowercase 'no':
```elixir
iex> Ymlr.document!(%{foo: "no"})
"---\nfoo: 'no'\n"
```

#### Link to documentation

https://yaml.org/type/bool.html

**Comment by Zinggi** [comment]
However, it seems like yaml 1.2 dropped this insane handling of boolean values and only accepts `true|false`.
So which version of the spec does this library actually target?

At the very least, it's an inconsistency, as it handles lowercase `no` like yaml 1.1, but uppercase like yaml 1.2.

**Comment by Zinggi** [comment]
As for me, I think I will switch to using https://github.com/processone/fast_yaml for my project, as I need 1-to-1 compatibility with the ruby yaml library. And since fast_yaml uses the same underlying libyaml, it should provide max compatibility between the two.

**Comment by Zinggi** [comment]
fast_yaml seems to handle this case correctly, but unfortunately I get the "wrong" quotes. Not great either for my usecase...
```
iex> :fast_yaml.encode(%{foo: "No"}) |> IO.iodata_to_binary
"foo: \"No\""
```

**Comment by mruoss** [comment]
Hi @Zinggi 

Thanks for raising this.

> So which version of the spec does this library actually target?

The quoted version is valid in both versions. So let's aim for that.
