### ISSUE TITLE
Dates are written with spaces

### ISSUE THREAD

**Issue by ArthurClemens** [ufirstgroup/ymlr#87]
Given a resource struct:
```elixir
[
  %{
    inserted_at: ~U[2022-07-31 14:48:48.000000Z]
  }
]
```

The YAML output is:
```yaml
- inserted_at:
    2022-07-31 14:48:48.000000000 Z
```

When reading this data back in the application, this is not directly usable to create dates with.

For comparison, Jason encodes this as:
```json
[
  {
    "inserted_at": "2022-07-31T14:48:48.000000Z"
  }
]
```
which can directly be read using `DateTime.from_iso8601()`

**Comment by jlgeering** [comment]
https://yaml.org/type/timestamp.html

current implementation returns a valid timestamp but not in the canonical format => probably better to switch

would require a major version bump => @mruoss what do you think?

**Comment by mruoss** [comment]
Yes thanks. Was about to check on yaml.org. Maybe we should have an issue template whwere it asks to point to official doc.

So yes, according to doc, the current version is valid YAML but not canonical. Should it be? And yes, would be a major version. And not adapted to the 1.x version.

**Comment by mruoss** [comment]
Ooops, wrong button, sorry.

**Comment by jlgeering** [comment]
@mruoss for now, I'm would opt to not make this configurable (wait for a concrete need to add some form of DateTime format option / param)

**Comment by mruoss** [comment]
@jlgeering Make _what_ configuratble? The output format? I would not make that configurable...

**Comment by jlgeering** [comment]
@joerichsen FYI this change might impact you

**Comment by joerichsen** [comment]
I added the PR with DateTime support in order to read YAML stored in strings in our database, where data is stored by a Ruby on Rails application.

So I just added the same format as Ruby stored it in in the PR.

But I just checked and it seems like Ruby is able to read the canonical format just fine as well, so I think that using the canonical format instead makes more sense 👍

**Comment by mruoss** [comment]
Perfect. Thanks for your heads up @joerichsen.
